### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by johaywood** [cmar/untappd#12]
Are you still maintaining this gem? Would you consider transferring ownership if 'no'?

**Comment by cmar** [comment]
@johaywood johaywood thanks for asking.The gem is in need of some upgrades. I've been doing a lot of client gem coding at work. It's on my todo list to get back to this gem to follow modern ruby styles.

Do you have a blocking issue right now?

**Comment by johaywood** [comment]
No, no real blocking issue. I was planning to use Untappd for a personal project I'm working on and came across this, but noticed it hasn't been updated in a while so I wanted to see if you'd be open to accepting PRs or if you had completely abandoned it. Sounds like you're hoping to pick it back up so I'll fork it and send PRs your way.
